name: Go

on:
  push:
    branches: [ andreasschulze-patch-1 ]
  pull_request:
    branches: [ andreasschulze-patch-1 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: go get
      run: go get -v github.com/andreasschulze/scmdhttpd@andreasschulze-patch-1

    - name: go install
      run: go install -v github.com/andreasschulze/scmdhttpd@andreasschulze-patch-1
