name: gobuild
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '5 5 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: go build
        run: go build -v
